baseURL = "https://otit.fi/"
languageCode = "fi"
title = "Oulun Tietoteekkarit ry"
theme = "mainroad"
paginate = "8" # Number of posts per page



[Author] # Used in authorbox
    name = "Oulun Tietoteekkarit ry"

[Params]
    copyright = "Oulun Tietoteekkarit ry" # Footer copyright holder, otherwise will use site title
    toc = true # Enable Table of Contents
    pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
    authorbox = false
    post_meta = ["date", "categories"] # Order of post meta information
    footer_heading = "Kannatusjäsenet"
    mainSections = ["uutiset"]

[Params.style.vars]
    # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
    # Take care of different quotes OR escaping symbols in these params if necessary
    fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
    fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
    #highlightColor = "#e22d30" # Override highlight color
    highlightColor = "#3e00c8" # Override highlight color


[Params.logo]
    image = "img/logoo.png" # Logo image. Path relative to "static"
    backgroundimage = "/img/IMG_3562.jpeg"
    title = "Oulun Tietoteekkarit ry" # Logo title, otherwise will use site title
    subtitle = "" # Logo subtitle

[Params.sidebar]
    home = "right" # Configure layout for home page
    list = "right"  # Configure layout for list pages
    single = "right" # Configure layout for single pages
    # Enable widgets in given order
    # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]
    # alternatively "ddg-search" can be used, to search via DuckDuckGo
    # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]
    widgets = ["ddg-search", "sidemenu", "recent", "calendar", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget







########################################
####                ####################
####    MENU        ####################
####                ####################
########################################

[menu]

########################################
####                ####################
####    MAIN MENU   ####################
####                ####################
########################################

  [[menu.main]]
    identifier = "etusivu"
    name = "Etusivu"
    url = "/"
    weight = 1


  [[menu.main]]
    identifier = "kilta"
    name = "Kilta"
    url = "/kilta/"
    weight = 2
    [[menu.main]]
      identifier = "yhteystiedot"
      name = "Yhteystiedot"
      url = "/kilta/yhteystiedot"
      parent = "kilta"
      weight = 1
    [[menu.main]]
      identifier = "hallitus"
      name = "Hallitus"
      url = "/kilta/hallitus"
      parent = "kilta"
      weight = 2
    [[menu.main]]
      identifier = "toimihenkilot"
      name = "Toimihenkilöt"
      url = "/kilta/toimihenkilot"
      parent = "kilta"
      weight = 3
    [[menu.main]]
      identifier = "historia"
      name = "Historia"
      url = "/kilta/historia"
      parent = "kilta"
      weight = 4
    [[menu.main]]
      identifier = "saannot"
      name = "Säännöt"
      url = "/kilta/saannot"
      parent = "kilta"
      weight = 5


  [[menu.main]]
    identifier = "toiminta"
    name = "Toiminta"
    url = "/toiminta/"
    weight = 3
    [[menu.main]]
      identifier = "kiltahuone"
      name = "Kiltahuone"
      url = "/toiminta/kiltahuone"
      parent = "toiminta"
      weight = 1
    [[menu.main]]
      identifier = "otitsunii"
      name = "otitsunii"
      url = "/toiminta/otitsunii"
      parent = "toiminta"
      weight = 2
    [[menu.main]]
      identifier = "terminaali"
      name = "Terminaali"
      url = "/toiminta/terminaali"
      parent = "toiminta"
      weight = 3
    [[menu.main]]
      identifier = "laulut"
      name = "Laulut"
      url = "/toiminta/laulut"
      parent = "toiminta"
      weight = 4


  [[menu.main]]
    identifier = "fuksit"
    name = "Fuksit"
    url = "/fuksit/"
    weight = 4
    [[menu.main]]
      identifier = "pienryhmaohjaajat"
      name = "Pienryhmäohjaajat"
      url = "/fuksit/pienryhmaohjaajat"
      parent = "fuksit"
      weight = 1
    [[menu.main]]
      identifier = "tietopaketti"
      name = "Tietopaketti"
      url = "/fuksit/tietopaketti"
      parent = "fuksit"
      weight = 2
    [[menu.main]]
      identifier = "ukk"
      name = "UKK"
      url = "/fuksit/ukk"
      parent = "fuksit"
      weight = 3


  [[menu.main]]
    identifier = "yritykset"
    name = "Yritykset"
    url = "/yritykset/"
    weight = 5


  [[menu.main]]
    identifier = "tietopankki"
    name = "Tietopankki"
    url = "/tietopankki/"
    weight = 6
    [[menu.main]]
      identifier = "irc-opas"
      name = "IRC-opas"
      url = "/tietopankki/irc-opas"
      parent = "tietopankki"
      weight = 1
    [[menu.main]]
      identifier = "astiasto"
      name = "Astiasto"
      url = "/tietopankki/astiasto"
      parent = "tietopankki"
      weight = 2
    [[menu.main]]
      identifier = "laskutuspohja"
      name = "Laskutuspohja"
      url = "/tietopankki/laskutuspohja"
      parent = "tietopankki"
      weight = 3
    [[menu.main]]
      identifier = "tenttiarkisto"
      name = "Tenttiarkisto"
      url = "/tietopankki/tenttiarkisto"
      parent = "tietopankki"
      weight = 4
    [[menu.main]]
      identifier = "jasenhakemus"
      name = "Jäsenhakemus"
      url = "/tietopankki/jasenhakemus"
      parent = "tietopankki"
      weight = 5
    [[menu.main]]
      identifier = "hyodyllisia-ohjelmia-opiskelijoille"
      name = "Hyödyllisiä ohjelmia opiskelijoille"
      url = "/tietopankki/hyodyllisia-ohjelmia-opiskelijoille"
      parent = "tietopankki"
      weight = 6
    [[menu.main]]
      identifier = "tietosuojaselosteet"
      name = "Tietosuojaselosteet"
      url = "/tietopankki/tietosuojaselosteet"
      parent = "tietopankki"
      weight = 7
    [[menu.main]]
      identifier = "otitsunii-tunnushakemus"
      name = "otitsunii-tunnushakemus"
      url = "/tietopankki/otitsunii-tunnushakemus"
      parent = "tietopankki"
      weight = 8


#  [[menu.main]]
#    identifier = "galleria"
#    name = "Galleria"
#    url = "/galleria/"
#    weight = 7

#  [[menu.main]]
#    identifier = "palaute"
#    name = "Palaute"
#    url = "/palaute/"
#    weight = 8

########################################
####                    ################
####    END MAIN MENU   ################
####                    ################
########################################


########################################
####                   #################
####    LOGOS          #################
####                   #################
########################################

  [[menu.footer]]
    identifier = "startuplifers-logo"
    name = ""
    url = "https://startuplifers.org/"
    pre = "<a href='https://startuplifers.org/'><img src='/img/Startuplifers_Logo_Red_RGB_medium-1.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "boogie-logo"
    name = ""
    url = "https://boogiesoftware.com/"
    pre = "<a href='https://boogiesoftware.com/'><img src='/img/boogie_logo-e1584384843857.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "buutti-logo"
    name = ""
    url = "https://buutti.com/"
    pre = "<a href='https://buutti.com/'><img src='/img/Buutti-Logo.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "codemate-logo"
    name = ""
    url = "https://www.codemate.com/"
    pre = "<a href='https://www.codemate.com/'><img src='/img/codemate-Logo-tagline-white-nobg.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "mediatek-logo"
    name = ""
    url = "https://www.mediatek.com/"
    pre = "<a href='https://www.mediatek.com/'><img src='/img/MTK-logo.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "siili-logo"
    name = ""
    url = "https://www.siili.com/"
    pre = "<a href='https://www.siili.com/'><img src='/img/Siili_logo_text_8_spikes_Black_RGB_28042020.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "synopsys-logo"
    name = ""
    url = "https://www.synopsys.com/"
    pre = "<a href='https://www.synopsys.com/'><img src='/img/snps-logo-sts-purple-grey-e1581696903879.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "verkotan-logo"
    name = ""
    url = "https://verkotan.com/"
    pre = "<a href='https://verkotan.com/'><img src='/img/verkotan.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1
  [[menu.footer]]
    identifier = "visidon-logo"
    name = ""
    url = "https://www.visidon.fi/"
    pre = "<a href='https://www.visidon.fi/'><img src='/img/Visidon_logo_RGB_1200dpi_white.png' style='padding: 20px; max-height: 140px; max-width: 220px;'></a>"
    weight = 1

########################################
####                   #################
####    ENDLOGOS       #################
####                   #################
########################################

########################################
####                   #################
####    ENDMENU        #################
####                   #################
########################################